version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000

  api:
    build: api
    ports:
      - 5555:5000
  mysql:
    image: mysql


  adminer:
    image: adminer 
    ports:
      - 8888:8080